# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow"]
# ///
"""Find, fetch and credit real photos and recorded sounds for the decks (free licences only).

Run with uv (pulls Pillow):  uv run tools/media.py <command> ...

  img-search "<query>" [--n 12] [--drawing]      Wikimedia Commons search -> numbered list + contact sheet PNG
  img-add <dest> <id> "<File:… title>" [--crop L,T,R,B] [--max 1200] [--replace] [--title "…"]
                                                  download, crop (fractions 0..1), resize, JPEG -> <dest>/media/<id>.jpg
  snd-search "<query>" [--n 12] [--src fs|commons|all] [--maxdur 40] [--sort downloads|rating|relevance]
                                                  Freesound (CC0 + CC BY) and Commons audio -> list + waveform sheet
  snd-add <dest> <id> <freesound-id | "File:….ogg"> [--start S] [--dur S] [--fadeout S] [--gain DB] [--title "…"]
                                                  download, trim, normalise, mono MP3 -> <dest>/media/<id>.mp3 (+ waveform PNG)
  info <dest> <id> | rm <dest> <id> | list <dest>
  lint <subject>                                  every photo/sound id used in <subject>/units exists; unused media

<dest> is a subject folder (mathe, deutsch, englisch, nawi, gewi, musik, kunst) or "shared".
Ids: lowercase a-z 0-9 and dashes. A subject id may not reuse a shared id.
Each dest keeps media/credits.json (source of truth) and media/credits.js (generated, loaded by the page).
Allowed licences: public domain / CC0 / CC BY / CC BY-SA. NC and ND are refused.
"""
import html
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "tools", ".cache")
UA = "klasse5-edu/1.0 (family learning app; me@bensarmiento.com)"
BROWSER_UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
SUBJECTS = ["mathe", "deutsch", "englisch", "nawi", "gewi", "musik", "kunst"]
FFMPEG = shutil.which("ffmpeg") or "/opt/homebrew/bin/ffmpeg"
FFPROBE = shutil.which("ffprobe") or "/opt/homebrew/bin/ffprobe"


def die(msg):
    print("ERROR: " + msg, file=sys.stderr)
    sys.exit(1)


def get(url, ua=UA, binary=False, tries=3):
    last = None
    for _ in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": ua})
            with urllib.request.urlopen(req, timeout=60) as r:
                data = r.read()
                return data if binary else data.decode("utf-8", "replace")
        except Exception as e:  # noqa: BLE001
            last = e
            import time
            time.sleep(2)
    die(f"download failed {url}: {last}")


def strip_tags(s):
    s = re.sub(r"<[^>]+>", "", s or "")
    return re.sub(r"\s+", " ", html.unescape(s)).strip()


def licence_ok(name):
    n = (name or "").lower()
    if not n or re.search(r"\bnc\b|\bnd\b|non-?commercial|noderiv", n):
        return False
    return bool(re.search(r"public domain|^pd|cc0|cc[- ]?by|attribution|cc-pd", n))


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:50]


def opt(args, name, default=None):
    if name in args:
        i = args.index(name)
        v = args[i + 1]
        del args[i:i + 2]
        return v
    return default


def flag(args, name):
    if name in args:
        args.remove(name)
        return True
    return False


# ---------------------------------------------------------------- credits store
def dest_dir(dest):
    if dest != "shared" and dest not in SUBJECTS:
        die(f"unknown dest {dest!r}; use one of {SUBJECTS} or shared")
    d = os.path.join(ROOT, dest, "media")
    os.makedirs(d, exist_ok=True)
    return d


def load_credits(dest):
    p = os.path.join(dest_dir(dest), "credits.json")
    return json.load(open(p)) if os.path.exists(p) else {}


def save_credits(dest, cr):
    d = dest_dir(dest)
    cr = dict(sorted(cr.items()))
    json.dump(cr, open(os.path.join(d, "credits.json"), "w"), ensure_ascii=False, indent=1)
    base = "../shared/media/" if dest == "shared" else "media/"
    slim = {k: {kk: vv for kk, vv in v.items() if kk not in ("orig", "added")} for k, v in cr.items()}
    with open(os.path.join(d, "credits.js"), "w") as f:
        f.write("/* generated by tools/media.py – edit credits.json via the tool, not by hand */\n")
        f.write(f"Deck.media({json.dumps(base)}, {json.dumps(slim, ensure_ascii=False, separators=(',', ':'))});\n")


class locked:
    """exclusive lock on <dest>/media while reading-modifying-writing credits.json (several agents may add at once)"""
    def __init__(self, dest):
        self.path = os.path.join(dest_dir(dest), ".lock")

    def __enter__(self):
        import fcntl
        self.f = open(self.path, "w")
        fcntl.flock(self.f, fcntl.LOCK_EX)

    def __exit__(self, *a):
        import fcntl
        fcntl.flock(self.f, fcntl.LOCK_UN)
        self.f.close()


def check_id(dest, mid, replace=False):
    if not replace and mid in load_credits(dest):
        die(f"{mid!r} already exists in {dest} ({load_credits(dest)[mid]['title']}) – use it, pick another id, or pass --replace")
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]{1,48}", mid):
        die("id must be lowercase a-z, 0-9, dashes (2–49 chars)")
    if dest != "shared" and mid in load_credits("shared"):
        die(f"{mid!r} already exists in shared – just use it, or pick another id")


def _put(dest, mid, entry):
    cr = load_credits(dest)
    cr[mid] = entry
    save_credits(dest, cr)


# ---------------------------------------------------------------- Commons
def commons_api(params):
    params = dict(params, format="json", formatversion="2")
    return json.loads(get("https://commons.wikimedia.org/w/api.php?" + urllib.parse.urlencode(params)))


def commons_info(titles, width=1400):
    r = commons_api({"action": "query", "titles": "|".join(titles), "prop": "imageinfo",
                     "iiprop": "url|size|extmetadata|mime", "iiurlwidth": width})
    out = []
    for p in r.get("query", {}).get("pages", []):
        if "imageinfo" not in p:
            continue
        ii = p["imageinfo"][0]
        md = ii.get("extmetadata", {})
        lic = md.get("LicenseShortName", {}).get("value", "")
        out.append({
            "title": p["title"], "w": ii.get("width"), "h": ii.get("height"), "mime": ii.get("mime"),
            "url": ii.get("url"), "thumb": ii.get("thumburl") or ii.get("url"),
            "page": ii.get("descriptionurl"),
            "license": strip_tags(lic), "license_url": md.get("LicenseUrl", {}).get("value", ""),
            "author": strip_tags(md.get("Artist", {}).get("value", "")) or strip_tags(md.get("Credit", {}).get("value", "")),
            "desc": strip_tags(md.get("ImageDescription", {}).get("value", ""))[:160],
            "duration": ii.get("duration"),
        })
    return out


def contact_sheet(items, path, label_fn, thumb_key="thumb", tw=300, th=210, cols=4):
    from PIL import Image, ImageDraw, ImageFont
    rows = (len(items) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * tw, rows * (th + 26)), "white")
    d = ImageDraw.Draw(sheet)
    try:
        font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial Bold.ttf", 18)
    except Exception:  # noqa: BLE001
        font = ImageFont.load_default()
    import io
    for i, it in enumerate(items):
        x, y = (i % cols) * tw, (i // cols) * (th + 26)
        try:
            im = Image.open(io.BytesIO(get(it[thumb_key], binary=True))).convert("RGB")
            im.thumbnail((tw - 8, th - 8))
            sheet.paste(im, (x + (tw - im.width) // 2, y + 26 + (th - im.height) // 2))
        except Exception as e:  # noqa: BLE001
            d.text((x + 10, y + 60), f"(no preview: {e})"[:40], fill="red", font=font)
        d.text((x + 6, y + 3), label_fn(i, it)[:32], fill="black", font=font)
    sheet.save(path)
    return path


def img_search(args):
    n = int(opt(args, "--n", 12))
    drawing = flag(args, "--drawing")
    q = " ".join(args)
    if not q:
        die("query missing")
    ft = "filetype:drawing" if drawing else "filetype:bitmap filew:>640"
    r = commons_api({"action": "query", "list": "search", "srnamespace": 6, "srlimit": min(50, n * 3),
                     "srsearch": f"{q} {ft}"})
    titles = [x["title"] for x in r.get("query", {}).get("search", [])]
    infos = []
    for i in range(0, len(titles), 20):
        infos += commons_info(titles[i:i + 20], width=400)
    order = {t: i for i, t in enumerate(titles)}
    infos.sort(key=lambda x: order.get(x["title"], 99))
    ok = [x for x in infos if licence_ok(x["license"])][:n]
    if not ok:
        print("no freely licensed results – try other words (English often works better)")
        return
    for i, x in enumerate(ok, 1):
        print(f"[{i}] {x['title']}\n     {x['w']}x{x['h']} · {x['license']} · {x['author'][:60]}\n     {x['desc'][:140]}")
    os.makedirs(os.path.join(CACHE, "sheets"), exist_ok=True)
    p = contact_sheet(ok, os.path.join(CACHE, "sheets", "img-" + slug(q) + ".png"), lambda i, it: f"[{i + 1}]")
    print(f"\ncontact sheet: {p}   (Read it to look at the candidates)")


def img_add(args):
    crop = opt(args, "--crop")
    mx = int(opt(args, "--max", 1200))
    title_override = opt(args, "--title")
    replace = flag(args, "--replace")
    if len(args) < 3:
        die('usage: img-add <dest> <id> "File:…"')
    dest, mid, title = args[0], args[1], " ".join(args[2:])
    check_id(dest, mid, replace)
    if not title.startswith("File:"):
        title = "File:" + title
    info = commons_info([title], width=max(mx, 1400))
    if not info:
        die(f"not found on Commons: {title}")
    x = info[0]
    if not licence_ok(x["license"]):
        die(f"licence not allowed: {x['license']!r}")
    from PIL import Image
    import io
    raw = get(x["thumb"], binary=True)
    im = Image.open(io.BytesIO(raw))
    if im.mode in ("RGBA", "LA", "P"):
        im = im.convert("RGBA")
        bg = Image.new("RGBA", im.size, "white")
        bg.alpha_composite(im)
        im = bg
    im = im.convert("RGB")
    if crop:
        l, t, r, b = [float(v) for v in crop.split(",")]
        W, H = im.size
        im = im.crop((int(l * W), int(t * H), int(r * W), int(b * H)))
    im.thumbnail((mx, mx), Image.LANCZOS)
    d = dest_dir(dest)
    out = os.path.join(d, mid + ".jpg")
    im.save(out, "JPEG", quality=80, optimize=True, progressive=True)
    with locked(dest):
        _put(dest, mid, {"file": mid + ".jpg", "kind": "img", "w": im.width, "h": im.height,
               "title": title_override or re.sub(r"\.\w+$", "", x["title"][5:]).replace("_", " "),
               "author": x["author"][:120] or "unbekannt", "license": x["license"], "license_url": x["license_url"],
               "source": x["page"], "orig": x["title"]})
    print(f"saved {os.path.relpath(out, ROOT)} {im.width}x{im.height} {os.path.getsize(out) // 1024} KB · {x['license']} · {x['author'][:60]}")


# ---------------------------------------------------------------- Freesound + Commons audio
def fs_search(q, n, sort):
    s = {"downloads": "Downloads (most first)", "rating": "Rating (highest first)"}.get(sort, "Automatic by relevance")
    url = "https://freesound.org/search/?" + urllib.parse.urlencode(
        {"q": q, "f": 'license:("Creative Commons 0" OR "Attribution")', "s": s})
    h = get(url, ua=BROWSER_UA)
    out = []
    for m in re.finditer(r'<div\s+class="bw-player"(.*?)</div>\s*</div>\s*<div class="col-8(.*?)bw-player__tags-list-height(.*?)</div>\s*</div>\s*</div>', h, re.S):
        a, b, c = m.groups()
        attr = dict(re.findall(r'data-([a-z-]+)="([^"]*)"', a))
        desc = strip_tags(re.search(r'overflow-hidden v-spacing-1"\s*>(.*?)</div>', b, re.S).group(1)) if re.search(r'overflow-hidden v-spacing-1"\s*>(.*?)</div>', b, re.S) else ""
        tags = [strip_tags(t) for t in re.findall(r'/browse/tags/[^"]*"[^>]*>(.*?)</a>', c, re.S)][:8]
        out.append({"src": "fs", "id": attr.get("sound-id"), "title": html.unescape(attr.get("title", "")),
                    "user": attr.get("username"), "dur": float(attr.get("duration", 0) or 0),
                    "downloads": attr.get("num-downloads"), "mp3": attr.get("mp3", "").replace("-lq.mp3", "-hq.mp3"),
                    "wave": attr.get("waveform"), "desc": desc[:150], "tags": tags})
        if len(out) >= n:
            break
    return out


def commons_snd_search(q, n):
    r = commons_api({"action": "query", "list": "search", "srnamespace": 6, "srlimit": min(40, n * 3),
                     "srsearch": f"{q} filetype:audio"})
    titles = [x["title"] for x in r.get("query", {}).get("search", [])]
    infos = []
    for i in range(0, len(titles), 20):
        infos += commons_info(titles[i:i + 20], width=200)
    out = []
    for x in infos:
        if not licence_ok(x["license"]):
            continue
        out.append({"src": "commons", "id": x["title"], "title": x["title"][5:], "user": x["author"][:40],
                    "dur": float(x.get("duration") or 0), "downloads": "-", "mp3": x["url"], "wave": None,
                    "desc": x["desc"], "tags": [], "license": x["license"]})
        if len(out) >= n:
            break
    return out


def snd_search(args):
    n = int(opt(args, "--n", 12))
    src = opt(args, "--src", "all")
    maxdur = float(opt(args, "--maxdur", 60))
    sort = opt(args, "--sort", "relevance")
    q = " ".join(args)
    res = []
    if src in ("fs", "all"):
        res += [r for r in fs_search(q, n * 2, sort) if r["dur"] <= maxdur][:n]
    if src in ("commons", "all"):
        res += [r for r in commons_snd_search(q, n) if not r["dur"] or r["dur"] <= maxdur][: (n if src == "commons" else max(4, n // 3))]
    if not res:
        print("nothing found – try English words, fewer words, or --src commons")
        return
    for i, r in enumerate(res, 1):
        ident = f"freesound {r['id']}" if r["src"] == "fs" else r["id"]
        print(f"[{i}] {ident} · {r['title'][:60]} · {r['dur']:.1f}s · by {r['user']} · dl {r['downloads']}"
              + (f" · {r.get('license')}" if r.get("license") else ""))
        if r["desc"] or r["tags"]:
            print(f"     {r['desc'][:130]}  tags: {', '.join(r['tags'])}")
    waves = [r for r in res if r.get("wave")]
    if waves:
        os.makedirs(os.path.join(CACHE, "sheets"), exist_ok=True)
        p = contact_sheet(waves, os.path.join(CACHE, "sheets", "snd-" + slug(q) + ".png"),
                          lambda i, it: f"[{res.index(it) + 1}] {it['dur']:.1f}s", thumb_key="wave", tw=360, th=110, cols=3)
        print(f"\nwaveform sheet (freesound only): {p}")


def fs_meta(sid):
    page = get(f"https://freesound.org/s/{sid}/", ua=BROWSER_UA)
    lic = re.search(r'creativecommons\.org/(licenses/[a-z-]+/[\d.]+|publicdomain/zero/[\d.]+)', page)
    if not lic:
        die(f"freesound {sid}: no licence found")
    lic = lic.group(1)
    name = {"publicdomain/zero": "CC0 1.0"}
    lname = "CC0 1.0" if lic.startswith("publicdomain") else "CC " + lic.split("/")[1].upper() + " " + lic.split("/")[2]
    if not licence_ok(lname):
        die(f"freesound {sid}: licence not allowed ({lname})")
    og = dict(re.findall(r'<meta property="og:([a-z]+)" content="([^"]*)"', page))
    title = html.unescape(og.get("title", ""))
    m = re.match(r"(.*) by (.*)$", title)
    t, user = (m.group(1), m.group(2)) if m else (title, "")
    mp3 = re.search(r'https://cdn\.freesound\.org/previews/\d+/\d+_\d+-lq\.mp3', page)
    if not mp3:
        die(f"freesound {sid}: no preview url")
    return {"title": t, "author": user, "license": lname, "license_url": "https://creativecommons.org/" + lic + "/",
            "source": og.get("url") or f"https://freesound.org/s/{sid}/", "url": mp3.group(0).replace("-lq.mp3", "-hq.mp3")}


def probe_dur(path):
    out = subprocess.run([FFPROBE, "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", path], capture_output=True, text=True).stdout.strip()
    try:
        return float(out)
    except ValueError:
        return 0.0


def snd_add(args):
    start = float(opt(args, "--start", 0))
    dur = opt(args, "--dur")
    fadeout = float(opt(args, "--fadeout", 0.25))
    gain = float(opt(args, "--gain", 0))
    title_override = opt(args, "--title")
    keep_silence = flag(args, "--keep-silence")
    replace = flag(args, "--replace")
    if len(args) < 3:
        die("usage: snd-add <dest> <id> <freesound-id | File:…>")
    dest, mid, ref = args[0], args[1], " ".join(args[2:])
    check_id(dest, mid, replace)
    if re.fullmatch(r"(freesound\s*)?\d+", ref):
        sid = re.sub(r"\D", "", ref)
        meta = fs_meta(sid)
    else:
        t = ref if ref.startswith("File:") else "File:" + ref
        info = commons_info([t])
        if not info:
            die(f"not found on Commons: {t}")
        x = info[0]
        if not licence_ok(x["license"]):
            die(f"licence not allowed: {x['license']!r}")
        meta = {"title": re.sub(r"\.\w+$", "", x["title"][5:]).replace("_", " "), "author": x["author"][:120] or "unbekannt",
                "license": x["license"], "license_url": x["license_url"], "source": x["page"], "url": x["url"]}
    tmp = tempfile.mkdtemp()
    src = os.path.join(tmp, "in" + os.path.splitext(urllib.parse.urlparse(meta["url"]).path)[1])
    open(src, "wb").write(get(meta["url"], binary=True))
    d = dest_dir(dest)
    out = os.path.join(d, mid + ".mp3")
    filt = []
    if not keep_silence and start == 0:
        filt.append("silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.02")
    total = probe_dur(src)
    length = float(dur) if dur else max(0.1, total - start)
    filt.append(f"afade=t=out:st={max(0, length - fadeout):.3f}:d={fadeout:.3f}")
    filt.append("loudnorm=I=-17:TP=-1.5:LRA=11")
    if gain:
        filt.append(f"volume={gain}dB")
    cmd = [FFMPEG, "-y", "-v", "error", "-ss", str(start), "-i", src]
    if dur:
        cmd += ["-t", str(dur)]
    cmd += ["-af", ",".join(filt), "-ac", "1", "-ar", "44100", "-c:a", "libmp3lame", "-b:a", "112k", out]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        die("ffmpeg: " + r.stderr[-400:])
    # trailing silence check + waveform
    real = probe_dur(out)
    wave = os.path.join(CACHE, "waves")
    os.makedirs(wave, exist_ok=True)
    wpng = os.path.join(wave, f"{dest}-{mid}.png")
    subprocess.run([FFMPEG, "-y", "-v", "error", "-i", out, "-filter_complex", "showwavespic=s=900x160:colors=#1d5bd0", "-frames:v", "1", wpng])
    with locked(dest):
        _put(dest, mid, {"file": mid + ".mp3", "kind": "snd", "dur": round(real, 2), "title": title_override or meta["title"],
               "author": meta["author"], "license": meta["license"], "license_url": meta["license_url"],
               "source": meta["source"], "orig": ref})
    shutil.rmtree(tmp, ignore_errors=True)
    print(f"saved {os.path.relpath(out, ROOT)} {real:.2f}s {os.path.getsize(out) // 1024} KB · {meta['license']} · {meta['author']}\nwaveform: {wpng}")


# ---------------------------------------------------------------- misc
def lint(args):
    subj = args[0]
    used = {}
    for f in sorted(os.listdir(os.path.join(ROOT, subj, "units"))):
        if not f.endswith(".js"):
            continue
        src = open(os.path.join(ROOT, subj, "units", f)).read()
        for m in re.finditer(r'\b(photo|sound|soundBtn|preload)\(\s*["\'`]([\w.-]+)["\'`]', src):
            used.setdefault(m.group(2), set()).add(f)
    have = load_credits(subj)
    shared = load_credits("shared")
    bad = 0
    for mid, files in sorted(used.items()):
        m = have.get(mid) or shared.get(mid)
        where = subj if mid in have else "shared"
        if not m:
            print(f"MISSING id {mid!r} used in {', '.join(sorted(files))}")
            bad += 1
        elif not os.path.exists(os.path.join(ROOT, where, "media", m["file"])):
            print(f"MISSING FILE {where}/media/{m['file']}")
            bad += 1
    allsrc = "".join(open(os.path.join(ROOT, subj, "units", f)).read() for f in os.listdir(os.path.join(ROOT, subj, "units")) if f.endswith(".js"))
    unused = [k for k in have if k not in used and not re.search(r'["\'`]' + re.escape(k) + r'["\'`]', allsrc)]
    if unused:
        print("unused in " + subj + " (delete with rm, or use them): " + ", ".join(unused))
    nimg = sum(1 for k in used if (have.get(k) or shared.get(k) or {}).get("kind") == "img")
    print(json.dumps({"missing": bad, "ids_used": len(used), "photos_used": nimg, "sounds_used": len(used) - nimg, "unused": len(unused)}))


def main():
    a = sys.argv[1:]
    if not a:
        print(__doc__)
        return
    cmd, rest = a[0], a[1:]
    if cmd == "img-search":
        img_search(rest)
    elif cmd == "img-add":
        img_add(rest)
    elif cmd == "snd-search":
        snd_search(rest)
    elif cmd == "snd-add":
        snd_add(rest)
    elif cmd == "lint":
        lint(rest)
    elif cmd == "info":
        print(json.dumps(load_credits(rest[0]).get(rest[1]), ensure_ascii=False, indent=1))
    elif cmd == "list":
        for k, v in load_credits(rest[0]).items():
            print(f"{k:28} {v['kind']} {v.get('dur', '')} {v['title'][:50]} · {v['license']}")
    elif cmd == "rm":
      with locked(rest[0]):
        cr = load_credits(rest[0])
        m = cr.pop(rest[1], None)
        if m:
            try:
                os.remove(os.path.join(dest_dir(rest[0]), m["file"]))
            except FileNotFoundError:
                pass
            save_credits(rest[0], cr)
            print("removed", rest[1])
    else:
        die("unknown command " + cmd)


if __name__ == "__main__":
    main()
